/**
 * MR Comment Integration.
 *
 * Posts a GitPulse blast-radius report as a markdown note on a merge request,
 * so the analysis changes reviewer behavior instead of only printing to a log.
 *
 * Idempotent: the note carries a hidden marker. If a GitPulse note already
 * exists on the MR, it is updated in place rather than duplicated on every
 * pipeline run.
 *
 * Docs: https://docs.gitlab.com/api/notes/
 */

import { apiBaseUrl, authHeaders } from "./gitlab-api.js";

/** Hidden HTML marker used to find a previously-posted GitPulse note. */
export const REPORT_MARKER = "<!-- gitpulse-report -->";

/**
 * Render a blast-radius report object as a markdown MR comment body.
 * The first line is the hidden marker so the note can be located later.
 *
 * @param {object} report - Structured report from buildReport().
 * @returns {string} Markdown body.
 */
export function renderReportMarkdown(report) {
  const riskEmoji = { HIGH: "\uD83D\uDD34", MEDIUM: "\uD83D\uDFE1", LOW: "\uD83D\uDFE2" };
  const target = report.target.symbol
    ? `\`${report.target.file}::${report.target.symbol}()\``
    : `\`${report.target.file}\``;

  const lines = [];
  lines.push(REPORT_MARKER);
  lines.push(`## \uD83D\uDCCA GitPulse Blast Radius \u2014 ${target}`);
  lines.push("");

  if (!report.is_real_data) {
    lines.push(
      `> \u26A0\uFE0F **MOCK DATA** (source: \`${report.data_source}\`). Orbit was unavailable \u2014 not a real trace; do not use for merge decisions.`
    );
    lines.push("");
  } else if (report.data_source === "static-analysis") {
    lines.push(
      `> \u2139\uFE0F Dependency graph from local static import analysis (Orbit unavailable). Dependents are real; owner/MR data may be limited.`
    );
    lines.push("");
  }

  lines.push(`**${riskEmoji[report.risk] || "\u26AA"} ${report.risk_line}**`);
  lines.push("");
  lines.push(report.summary);
  lines.push("");

  const b = report.score_breakdown || {};
  lines.push("| Metric | Count |");
  lines.push("| --- | --- |");
  lines.push(`| Direct dependents | ${b.direct_dependents ?? 0} |`);
  lines.push(`| Transitive dependents | ${b.transitive_dependents ?? 0} |`);
  lines.push(`| Teams affected | ${b.teams_affected ?? 0} |`);
  lines.push(`| Open MR overlaps | ${b.open_mr_overlaps ?? 0} |`);
  lines.push(`| Pipelines at risk | ${b.pipelines_at_risk ?? 0} |`);
  lines.push("");

  if (report.open_mrs && report.open_mrs.length > 0) {
    lines.push("### \uD83D\uDD00 Open MRs touching related code");
    for (const mr of report.open_mrs) {
      lines.push(`- !${mr.id} \u2014 ${mr.title} (${mr.author})`);
    }
    lines.push("");
  }

  if (report.suggested_reviewers && report.suggested_reviewers.length > 0) {
    lines.push(`### \u2705 Suggested reviewers`);
    lines.push(report.suggested_reviewers.join(", "));
    lines.push("");
  }

  const mergeEmoji = report.safe_to_merge ? "\u2705" : "\uD83D\uDEAB";
  lines.push(
    `**Safe to merge without notifying these teams?** ${mergeEmoji} ${report.safe_to_merge ? "YES" : "NO"}`
  );
  lines.push("");
  lines.push(`<sub>Data source: \`${report.data_source}\` \u2014 generated by GitPulse</sub>`);

  return lines.join("\n");
}

/**
 * Find an existing GitPulse note (by marker) on the MR.
 * @returns {Promise<number|null>} Note id, or null if none / unavailable.
 */
async function findExistingNote(base, headers, projectId, mrIid) {
  const url = `${base}/projects/${encodeURIComponent(projectId)}/merge_requests/${mrIid}/notes?per_page=100`;
  const res = await fetch(url, { headers });
  if (!res.ok) return null;
  const notes = await res.json();
  if (!Array.isArray(notes)) return null;
  const existing = notes.find(
    (n) => typeof n.body === "string" && n.body.includes(REPORT_MARKER)
  );
  return existing ? existing.id : null;
}

/**
 * Post (or update) the report as an MR note.
 *
 * @param {object} report - Structured report object.
 * @param {object} opts
 * @param {string} opts.projectId
 * @param {number|string} opts.mrIid
 * @returns {Promise<{ ok: boolean, action: string, reason?: string }>}
 */
export async function postReportComment(report, { projectId, mrIid }) {
  if (typeof fetch !== "function") {
    return { ok: false, action: "skipped", reason: "fetch unavailable" };
  }
  const headers = authHeaders();
  if (!headers) {
    return { ok: false, action: "skipped", reason: "no GITLAB_TOKEN/CI_JOB_TOKEN" };
  }
  if (!mrIid) {
    return { ok: false, action: "skipped", reason: "no merge request iid" };
  }

  const base = apiBaseUrl();
  const body = renderReportMarkdown(report);
  const jsonHeaders = { "Content-Type": "application/json", ...headers };

  try {
    const existingId = await findExistingNote(base, headers, projectId, mrIid);
    const projPath = encodeURIComponent(projectId);

    if (existingId) {
      const res = await fetch(
        `${base}/projects/${projPath}/merge_requests/${mrIid}/notes/${existingId}`,
        { method: "PUT", headers: jsonHeaders, body: JSON.stringify({ body }) }
      );
      return res.ok
        ? { ok: true, action: "updated" }
        : { ok: false, action: "update-failed", reason: `HTTP ${res.status}` };
    }

    const res = await fetch(
      `${base}/projects/${projPath}/merge_requests/${mrIid}/notes`,
      { method: "POST", headers: jsonHeaders, body: JSON.stringify({ body }) }
    );
    return res.ok
      ? { ok: true, action: "created" }
      : { ok: false, action: "create-failed", reason: `HTTP ${res.status}` };
  } catch (error) {
    return { ok: false, action: "error", reason: error.message };
  }
}
